jobs:
  - job: Lint

    pool:
      vmImage: ubuntu-latest

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 12.x
        displayName: Install Node.js

      - bash: |
          echo node $(node --version)
          echo npm $(npm --version)
        displayName: Show node and npm version

      - script: npm ci
        displayName: Install dependencies

      - script: npm run test:other-than-unit-test
        displayName: Run linter
        timeoutInMinutes: 2

    cancelTimeoutInMinutes: 1
