parameters:
  name: Linux
  vmImage: ubuntu-latest

jobs:
  - job: ${{ format('UnitTest_{0}', parameters.name) }}
    displayName: ${{ format('UnitTest / {0}', parameters.name) }}

    variables:
      - template: node-versions.yml

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        ${{ each nodeVersion in variables.nodeVersions }}:
          ${{ format('Node.js {0}', nodeVersion) }}:
            node_version: ${{ nodeVersion }}

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js

      - bash: |
          echo node $(node --version)
          echo npm $(npm --version)
        displayName: Show node and npm version

      - script: npm ci || npm install
        displayName: Install dependencies

      - script: npm run test:unit-test
        displayName: Run unit test

    timeoutInMinutes: 3
    cancelTimeoutInMinutes: 1
