# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

strategy:
  matrix:
    Node.js 8.10.0 / Linux:
      imageName: ubuntu-latest
      node_version: 8.10.0
    Node.js 8.10.0 / Windows:
      imageName: windows-latest
      node_version: 8.10.0
    Node.js 8.x / Linux:
      imageName: ubuntu-latest
      node_version: 8.x
    Node.js 8.x / Windows:
      imageName: windows-latest
      node_version: 8.x
    Node.js 9.0.0 / Linux:
      imageName: ubuntu-latest
      node_version: 9.0.0
    Node.js 9.0.0 / Windows:
      imageName: windows-latest
      node_version: 9.0.0
    Node.js 9.x / Linux:
      imageName: ubuntu-latest
      node_version: 9.x
    Node.js 9.x / Windows:
      imageName: windows-latest
      node_version: 9.x
    Node.js 10.0.0 / Linux:
      imageName: ubuntu-latest
      node_version: 10.0.0
    Node.js 10.0.0 / Windows:
      imageName: windows-latest
      node_version: 10.0.0
    Node.js 10.x / Linux:
      imageName: ubuntu-latest
      node_version: 10.x
    Node.js 10.x / Windows:
      imageName: windows-latest
      node_version: 10.x
    Node.js 11.0.0 / Linux:
      imageName: ubuntu-latest
      node_version: 11.0.0
    Node.js 11.0.0 / Windows:
      imageName: windows-latest
      node_version: 11.0.0
    Node.js 11.x / Linux:
      imageName: ubuntu-latest
      node_version: 11.x
    Node.js 11.x / Windows:
      imageName: windows-latest
      node_version: 11.x
    Node.js 12.0.0 / Linux:
      imageName: ubuntu-latest
      node_version: 12.0.0
    Node.js 12.0.0 / Windows:
      imageName: windows-latest
      node_version: 12.0.0
    Node.js 12.x / Linux:
      imageName: ubuntu-latest
      node_version: 12.x
    Node.js 12.x / Windows:
      imageName: windows-latest
      node_version: 12.x
    Node.js 13.0.0 / Linux:
      imageName: ubuntu-latest
      node_version: 13.0.0
    Node.js 13.0.0 / Windows:
      imageName: windows-latest
      node_version: 13.0.0
    Node.js 13.x / Linux:
      imageName: ubuntu-latest
      node_version: 13.x
    Node.js 13.x / Windows:
      imageName: windows-latest
      node_version: 13.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: Install Node.js

  - bash: |
      echo node $(node --version)
      echo npm $(npm --version)
    displayName: Show node and npm version

  - script: npm ci || npm install
    displayName: Install dependencies

  - script: npm test
    displayName: Run test
    condition: eq( variables['Agent.OS'], 'Linux' )

  - script: npm run test:ava
    displayName: Run test
    condition: ne( variables['Agent.OS'], 'Linux' )
