# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: Lint

    pool:
      vmImage: ubuntu-latest

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: 12.x
        displayName: Install Node.js

      - bash: |
          echo node $(node --version)
          echo npm $(npm --version)
        displayName: Show node and npm version

      - script: npm ci
        displayName: Install dependencies

      - script: npx run-s test:readme test:peer-deps lint
        displayName: Run linter

  - template: azure-pipelines/unit-test.yml
    parameters:
      displayName: Linux
      vmImage: ubuntu-latest

  - template: azure-pipelines/unit-test.yml
    parameters:
      displayName: Windows
      vmImage: windows-latest
