parameters:
  name: UnitTest
  displayName: Linux
  vmImage: ubuntu-latest
  nodeVersions:
    - 8.10.0
    - 8.x
    - 9.0.0
    - 9.x
    - 10.0.0
    - 10.x
    - 11.0.0
    - 11.x
    - 12.0.0
    - 12.x
    - 13.0.0
    - 13.x

jobs:
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    strategy:
      matrix:
        ${{ each nodeVersion in parameters.nodeVersions }}:
          ${{ format('Node.js {0}', nodeVersion) }}:
            node_version: ${{ nodeVersion }}

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: $(node_version)
        displayName: Install Node.js

      - bash: |
          echo node $(node --version)
          echo npm $(npm --version)
        displayName: Show node and npm version

      - script: npm ci || npm install
        displayName: Install dependencies

      - script: npm run test:ava
        displayName: Run unit test
